defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

data_dir: "data"

data_generator:
  _target_: dtc_gnn.data_generation.graph_data_generator.GraphDataGenerator
  data_directories:
    train: "data/train"
    val: "data/val"
  stabilizer_code:
    _target_: hydra.utils.get_class
    path: qecsim.models.rotatedplanar.RotatedPlanarCode
  error_model:
    _target_: dtc_gnn.error_models.DepolarizingErrorModel
  graph_transform:
    _target_: dtc_gnn.data_management.transforms.graph_syndrome.GraphSyndromeTransform
    edges_constraint: 5
  n_samples: 500000
  split_ratio: 0.8
  code_distances:
    - 4
    - 6
    - 8
  error_probabilities:
    - 0.005
    - 0.055
    - 0.085
    - 0.105
    - 0.135
