defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

data_dirs:
  train: "data/train"
  val: "data/val"

error_model:
  _target_: dtc_gnn.error_models.DepolarizingErrorModel

graph_transform:
  _target_: dtc_gnn.data_management.data_transforms.SyndromeToGraphTransform
  edges_constraint: 5

code_distances:
  - 3
  - 5
  - 7
  - 9

n_samples: 250000
split_ratio: 0.8
error_prob: 0.115
