defaults:
  - _self_
  - gnn_model: graph_conv_gnn.yaml

data_module:
  _target_: dtc_gnn.data_management.modules.graph_data_module.GraphDataModule
  dataset:
    _target_: hydra.utils.get_class
    path: dtc_gnn.data_management.modules.graph_dataset.GraphDataset
  data_train_dir: "data/train"
  data_val_dir: "data/val"
  code_dist: -1
  batch_size: 512

trainer:
  max_epochs: 800
  callbacks:
    monitor: val_loss
    mode: min
    verbose: True
    min_delta: 0.0001
    patience: 20
    save_top_k: 1
    model_filename: best_model
