defaults:
  - _self_
  - gnn_model: egat_conv_gnn.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

gnn_model_path: outputs/yyyy-mm-dd/hh-mm-dd/GNNLightningModule.ckpt
reports_dir: reports

simulator:
  _target_: dtc_gnn.simulation.decoding_simulator.Simulator
  stabilizer_code:
    _target_: hydra.utils.get_class
    path: qecsim.models.rotatedtoric.RotatedToricCode
  error_model:
    _target_: dtc_gnn.error_models.DepolarizingErrorModel
  graph_transform:
    _target_: dtc_gnn.data_management.transforms.graph_syndrome.GraphSyndromeTransform
    edges_constraint: 8
  num_shots: 1200
  code_distances:
    - 4
    - 6
    - 8
  max_error_prob: 0.35
  prob_space_num: 10
