defaults:
  - _self_
  - gnn_model: graph_conv_gnn.yaml

data_module:
  _target_: dtc_gnn.data_management.data_modules.GraphDataModule
  dataset:
    _target_: hydra.utils.get_class
    path: dtc_gnn.data_management.data_modules.GraphDataset
  data_train_dir: "data/train"
  data_val_dir: "data/val"
  data_test_dir: "data/test"
  code_dist: -1
  batch_size: 512

trainer:
  max_epochs: 1
  callbacks:
    monitor: val_loss
    mode: min
    verbose: False
    min_delta: 0.001
    patience: 15
    save_top_k: 1
    model_filename: best_model
